// Code generated by logcopter-gen; DO NOT EDIT.

package dbguard

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.go-go-host.internal.sitejs.dbguard")
