// Code generated by logcopter-gen; DO NOT EDIT.

package doc

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.go-go-host.cmd.go-go-host.doc")
