// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAdminAgents = `-- name: ListAdminAgents :many
SELECT
  a.id,
  a.org_id,
  o.slug AS org_slug,
  o.name AS org_name,
  a.name,
  a.status,
  a.created_by_user_id,
  a.created_at,
  a.last_seen_at,
  COUNT(DISTINCT g.site_id)::bigint AS grant_count
FROM agents a
JOIN orgs o ON o.id = a.org_id
LEFT JOIN agent_site_grants g ON g.agent_id = a.id
WHERE ($1::text IS NULL OR a.org_id = $1::text)
  AND ($2::text IS NULL OR a.status = $2::text)
GROUP BY a.id, a.org_id, o.slug, o.name, a.name, a.status, a.created_by_user_id, a.created_at, a.last_seen_at
ORDER BY o.slug, a.name
`

type ListAdminAgentsParams struct {
	OrgID  pgtype.Text `json:"org_id"`
	Status pgtype.Text `json:"status"`
}

type ListAdminAgentsRow struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	OrgSlug         string             `json:"org_slug"`
	OrgName         string             `json:"org_name"`
	Name            string             `json:"name"`
	Status          string             `json:"status"`
	CreatedByUserID string             `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	GrantCount      int64              `json:"grant_count"`
}

func (q *Queries) ListAdminAgents(ctx context.Context, arg ListAdminAgentsParams) ([]ListAdminAgentsRow, error) {
	rows, err := q.db.Query(ctx, listAdminAgents, arg.OrgID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminAgentsRow{}
	for rows.Next() {
		var i ListAdminAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.OrgSlug,
			&i.OrgName,
			&i.Name,
			&i.Status,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.GrantCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminAuditEvents = `-- name: ListAdminAuditEvents :many
SELECT id, org_id, actor_type, actor_id, action, resource_type, resource_id, ip_address, user_agent, metadata_json, created_at
FROM audit_log
WHERE ($1::text IS NULL OR org_id = $1::text)
  AND ($2::text IS NULL OR resource_id = $2::text)
  AND ($3::text IS NULL OR actor_type = $3::text)
  AND ($4::text IS NULL OR actor_id = $4::text)
  AND ($5::text IS NULL OR action = $5::text)
ORDER BY created_at DESC
LIMIT $6::int
`

type ListAdminAuditEventsParams struct {
	OrgID      pgtype.Text `json:"org_id"`
	ResourceID pgtype.Text `json:"resource_id"`
	ActorType  pgtype.Text `json:"actor_type"`
	ActorID    pgtype.Text `json:"actor_id"`
	Action     pgtype.Text `json:"action"`
	Limit      int32       `json:"limit"`
}

func (q *Queries) ListAdminAuditEvents(ctx context.Context, arg ListAdminAuditEventsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAdminAuditEvents,
		arg.OrgID,
		arg.ResourceID,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.IpAddress,
			&i.UserAgent,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminDeployments = `-- name: ListAdminDeployments :many
SELECT
  d.id,
  d.site_id,
  s.slug AS site_slug,
  s.primary_host,
  s.org_id,
  o.slug AS org_slug,
  o.name AS org_name,
  d.version,
  d.status,
  d.bundle_ref,
  d.unpacked_path,
  d.manifest_json,
  d.validation_json,
  d.created_by_type,
  d.created_by_id,
  d.created_at,
  d.activated_at
FROM deployments d
JOIN sites s ON s.id = d.site_id
JOIN orgs o ON o.id = s.org_id
WHERE ($1::text IS NULL OR s.org_id = $1::text)
  AND ($2::text IS NULL OR d.site_id = $2::text)
  AND ($3::text IS NULL OR d.status = $3::text)
ORDER BY d.created_at DESC
LIMIT $4::int
`

type ListAdminDeploymentsParams struct {
	OrgID  pgtype.Text `json:"org_id"`
	SiteID pgtype.Text `json:"site_id"`
	Status pgtype.Text `json:"status"`
	Limit  int32       `json:"limit"`
}

type ListAdminDeploymentsRow struct {
	ID             string             `json:"id"`
	SiteID         string             `json:"site_id"`
	SiteSlug       string             `json:"site_slug"`
	PrimaryHost    string             `json:"primary_host"`
	OrgID          string             `json:"org_id"`
	OrgSlug        string             `json:"org_slug"`
	OrgName        string             `json:"org_name"`
	Version        int32              `json:"version"`
	Status         string             `json:"status"`
	BundleRef      string             `json:"bundle_ref"`
	UnpackedPath   string             `json:"unpacked_path"`
	ManifestJson   []byte             `json:"manifest_json"`
	ValidationJson []byte             `json:"validation_json"`
	CreatedByType  string             `json:"created_by_type"`
	CreatedByID    string             `json:"created_by_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ActivatedAt    pgtype.Timestamptz `json:"activated_at"`
}

func (q *Queries) ListAdminDeployments(ctx context.Context, arg ListAdminDeploymentsParams) ([]ListAdminDeploymentsRow, error) {
	rows, err := q.db.Query(ctx, listAdminDeployments,
		arg.OrgID,
		arg.SiteID,
		arg.Status,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminDeploymentsRow{}
	for rows.Next() {
		var i ListAdminDeploymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.SiteSlug,
			&i.PrimaryHost,
			&i.OrgID,
			&i.OrgSlug,
			&i.OrgName,
			&i.Version,
			&i.Status,
			&i.BundleRef,
			&i.UnpackedPath,
			&i.ManifestJson,
			&i.ValidationJson,
			&i.CreatedByType,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.ActivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminOrgs = `-- name: ListAdminOrgs :many
SELECT
  o.id,
  o.slug,
  o.name,
  o.created_at,
  COUNT(DISTINCT m.user_id)::bigint AS member_count,
  COUNT(DISTINCT s.id)::bigint AS site_count,
  COUNT(DISTINCT d.id)::bigint AS deployment_count
FROM orgs o
LEFT JOIN memberships m ON m.org_id = o.id
LEFT JOIN sites s ON s.org_id = o.id
LEFT JOIN deployments d ON d.site_id = s.id
GROUP BY o.id, o.slug, o.name, o.created_at
ORDER BY o.slug
`

type ListAdminOrgsRow struct {
	ID              string             `json:"id"`
	Slug            string             `json:"slug"`
	Name            string             `json:"name"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	MemberCount     int64              `json:"member_count"`
	SiteCount       int64              `json:"site_count"`
	DeploymentCount int64              `json:"deployment_count"`
}

func (q *Queries) ListAdminOrgs(ctx context.Context) ([]ListAdminOrgsRow, error) {
	rows, err := q.db.Query(ctx, listAdminOrgs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminOrgsRow{}
	for rows.Next() {
		var i ListAdminOrgsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.MemberCount,
			&i.SiteCount,
			&i.DeploymentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminSites = `-- name: ListAdminSites :many
SELECT
  s.id,
  s.org_id,
  o.slug AS org_slug,
  o.name AS org_name,
  s.slug,
  s.name,
  s.primary_host,
  s.status,
  s.active_deployment_id,
  s.created_at,
  COALESCE(rs.status, 'stopped') AS runtime_status,
  COALESCE(rs.requests_total, 0)::bigint AS requests_total,
  COALESCE(rs.errors_total, 0)::bigint AS errors_total,
  COALESCE(rs.last_error, '') AS last_error
FROM sites s
JOIN orgs o ON o.id = s.org_id
LEFT JOIN runtime_status rs ON rs.site_id = s.id
ORDER BY o.slug, s.slug
`

type ListAdminSitesRow struct {
	ID                 string             `json:"id"`
	OrgID              string             `json:"org_id"`
	OrgSlug            string             `json:"org_slug"`
	OrgName            string             `json:"org_name"`
	Slug               string             `json:"slug"`
	Name               string             `json:"name"`
	PrimaryHost        string             `json:"primary_host"`
	Status             string             `json:"status"`
	ActiveDeploymentID string             `json:"active_deployment_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	RuntimeStatus      string             `json:"runtime_status"`
	RequestsTotal      int64              `json:"requests_total"`
	ErrorsTotal        int64              `json:"errors_total"`
	LastError          string             `json:"last_error"`
}

func (q *Queries) ListAdminSites(ctx context.Context) ([]ListAdminSitesRow, error) {
	rows, err := q.db.Query(ctx, listAdminSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminSitesRow{}
	for rows.Next() {
		var i ListAdminSitesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.OrgSlug,
			&i.OrgName,
			&i.Slug,
			&i.Name,
			&i.PrimaryHost,
			&i.Status,
			&i.ActiveDeploymentID,
			&i.CreatedAt,
			&i.RuntimeStatus,
			&i.RequestsTotal,
			&i.ErrorsTotal,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT
  u.id,
  u.email,
  u.display_name,
  u.created_at,
  u.last_login_at,
  EXISTS (SELECT 1 FROM platform_admins pa WHERE pa.user_id = u.id) AS platform_admin,
  COUNT(DISTINCT m.org_id)::bigint AS org_count
FROM users u
LEFT JOIN memberships m ON m.user_id = u.id
GROUP BY u.id, u.email, u.display_name, u.created_at, u.last_login_at
ORDER BY u.email, u.id
`

type ListAdminUsersRow struct {
	ID            string             `json:"id"`
	Email         string             `json:"email"`
	DisplayName   string             `json:"display_name"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LastLoginAt   pgtype.Timestamptz `json:"last_login_at"`
	PlatformAdmin bool               `json:"platform_admin"`
	OrgCount      int64              `json:"org_count"`
}

func (q *Queries) ListAdminUsers(ctx context.Context) ([]ListAdminUsersRow, error) {
	rows, err := q.db.Query(ctx, listAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminUsersRow{}
	for rows.Next() {
		var i ListAdminUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.CreatedAt,
			&i.LastLoginAt,
			&i.PlatformAdmin,
			&i.OrgCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
