// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: agents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (id, org_id, name, status, created_by_user_id, created_at, last_seen_at)
VALUES ($1, $2, $3, $4, $5, $6, NULL)
RETURNING id, org_id, name, status, created_by_user_id, created_at, last_seen_at
`

type CreateAgentParams struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	Name            string             `json:"name"`
	Status          string             `json:"status"`
	CreatedByUserID string             `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Status,
		arg.CreatedByUserID,
		arg.CreatedAt,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getAgent = `-- name: GetAgent :one
SELECT id, org_id, name, status, created_by_user_id, created_at, last_seen_at
FROM agents
WHERE id = $1
`

func (q *Queries) GetAgent(ctx context.Context, id string) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const listAgentSiteGrants = `-- name: ListAgentSiteGrants :many
SELECT agent_id, site_id, can_deploy, can_rollback, allowed_channels, allowed_paths, expires_at, created_at, updated_at
FROM agent_site_grants
WHERE agent_id = $1
ORDER BY site_id
`

func (q *Queries) ListAgentSiteGrants(ctx context.Context, agentID string) ([]AgentSiteGrant, error) {
	rows, err := q.db.Query(ctx, listAgentSiteGrants, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentSiteGrant{}
	for rows.Next() {
		var i AgentSiteGrant
		if err := rows.Scan(
			&i.AgentID,
			&i.SiteID,
			&i.CanDeploy,
			&i.CanRollback,
			&i.AllowedChannels,
			&i.AllowedPaths,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsByOrg = `-- name: ListAgentsByOrg :many
SELECT id, org_id, name, status, created_by_user_id, created_at, last_seen_at
FROM agents
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAgentsByOrg(ctx context.Context, orgID string) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgentsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Status,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentStatus = `-- name: UpdateAgentStatus :exec
UPDATE agents
SET status = $2
WHERE id = $1
`

type UpdateAgentStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) error {
	_, err := q.db.Exec(ctx, updateAgentStatus, arg.ID, arg.Status)
	return err
}

const upsertAgentSiteGrant = `-- name: UpsertAgentSiteGrant :one
INSERT INTO agent_site_grants (agent_id, site_id, can_deploy, can_rollback, allowed_channels, allowed_paths, expires_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $8)
ON CONFLICT (agent_id, site_id)
DO UPDATE SET can_deploy = EXCLUDED.can_deploy, can_rollback = EXCLUDED.can_rollback, allowed_channels = EXCLUDED.allowed_channels, allowed_paths = EXCLUDED.allowed_paths, expires_at = EXCLUDED.expires_at, updated_at = EXCLUDED.updated_at
RETURNING agent_id, site_id, can_deploy, can_rollback, allowed_channels, allowed_paths, expires_at, created_at, updated_at
`

type UpsertAgentSiteGrantParams struct {
	AgentID         string             `json:"agent_id"`
	SiteID          string             `json:"site_id"`
	CanDeploy       bool               `json:"can_deploy"`
	CanRollback     bool               `json:"can_rollback"`
	AllowedChannels []string           `json:"allowed_channels"`
	AllowedPaths    []string           `json:"allowed_paths"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertAgentSiteGrant(ctx context.Context, arg UpsertAgentSiteGrantParams) (AgentSiteGrant, error) {
	row := q.db.QueryRow(ctx, upsertAgentSiteGrant,
		arg.AgentID,
		arg.SiteID,
		arg.CanDeploy,
		arg.CanRollback,
		arg.AllowedChannels,
		arg.AllowedPaths,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i AgentSiteGrant
	err := row.Scan(
		&i.AgentID,
		&i.SiteID,
		&i.CanDeploy,
		&i.CanRollback,
		&i.AllowedChannels,
		&i.AllowedPaths,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
