// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO audit_log (id, org_id, actor_type, actor_id, action, resource_type, resource_id, ip_address, user_agent, metadata_json, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, org_id, actor_type, actor_id, action, resource_type, resource_id, ip_address, user_agent, metadata_json, created_at
`

type InsertAuditEventParams struct {
	ID           string             `json:"id"`
	OrgID        string             `json:"org_id"`
	ActorType    string             `json:"actor_type"`
	ActorID      string             `json:"actor_id"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   string             `json:"resource_id"`
	IpAddress    string             `json:"ip_address"`
	UserAgent    string             `json:"user_agent"`
	MetadataJson []byte             `json:"metadata_json"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.ID,
		arg.OrgID,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.IpAddress,
		arg.UserAgent,
		arg.MetadataJson,
		arg.CreatedAt,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ActorType,
		&i.ActorID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.IpAddress,
		&i.UserAgent,
		&i.MetadataJson,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditEventsForOrg = `-- name: ListAuditEventsForOrg :many
SELECT id, org_id, actor_type, actor_id, action, resource_type, resource_id, ip_address, user_agent, metadata_json, created_at
FROM audit_log
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListAuditEventsForOrgParams struct {
	OrgID string `json:"org_id"`
	Limit int32  `json:"limit"`
}

func (q *Queries) ListAuditEventsForOrg(ctx context.Context, arg ListAuditEventsForOrgParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditEventsForOrg, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.IpAddress,
			&i.UserAgent,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
