// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: deployments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateDeployment = `-- name: ActivateDeployment :exec
UPDATE deployments
SET status = 'active', activated_at = $2
WHERE id = $1
`

type ActivateDeploymentParams struct {
	ID          string             `json:"id"`
	ActivatedAt pgtype.Timestamptz `json:"activated_at"`
}

func (q *Queries) ActivateDeployment(ctx context.Context, arg ActivateDeploymentParams) error {
	_, err := q.db.Exec(ctx, activateDeployment, arg.ID, arg.ActivatedAt)
	return err
}

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (id, site_id, version, status, bundle_ref, unpacked_path, manifest_json, validation_json, created_by_type, created_by_id, created_at, activated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NULL)
RETURNING id, site_id, version, status, bundle_ref, unpacked_path, manifest_json, validation_json, created_by_type, created_by_id, created_at, activated_at
`

type CreateDeploymentParams struct {
	ID             string             `json:"id"`
	SiteID         string             `json:"site_id"`
	Version        int32              `json:"version"`
	Status         string             `json:"status"`
	BundleRef      string             `json:"bundle_ref"`
	UnpackedPath   string             `json:"unpacked_path"`
	ManifestJson   []byte             `json:"manifest_json"`
	ValidationJson []byte             `json:"validation_json"`
	CreatedByType  string             `json:"created_by_type"`
	CreatedByID    string             `json:"created_by_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.ID,
		arg.SiteID,
		arg.Version,
		arg.Status,
		arg.BundleRef,
		arg.UnpackedPath,
		arg.ManifestJson,
		arg.ValidationJson,
		arg.CreatedByType,
		arg.CreatedByID,
		arg.CreatedAt,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Version,
		&i.Status,
		&i.BundleRef,
		&i.UnpackedPath,
		&i.ManifestJson,
		&i.ValidationJson,
		&i.CreatedByType,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.ActivatedAt,
	)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, site_id, version, status, bundle_ref, unpacked_path, manifest_json, validation_json, created_by_type, created_by_id, created_at, activated_at
FROM deployments
WHERE id = $1
`

func (q *Queries) GetDeployment(ctx context.Context, id string) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Version,
		&i.Status,
		&i.BundleRef,
		&i.UnpackedPath,
		&i.ManifestJson,
		&i.ValidationJson,
		&i.CreatedByType,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.ActivatedAt,
	)
	return i, err
}

const listDeploymentsBySite = `-- name: ListDeploymentsBySite :many
SELECT id, site_id, version, status, bundle_ref, unpacked_path, manifest_json, validation_json, created_by_type, created_by_id, created_at, activated_at
FROM deployments
WHERE site_id = $1
ORDER BY version DESC
`

func (q *Queries) ListDeploymentsBySite(ctx context.Context, siteID string) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Version,
			&i.Status,
			&i.BundleRef,
			&i.UnpackedPath,
			&i.ManifestJson,
			&i.ValidationJson,
			&i.CreatedByType,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.ActivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextDeploymentVersion = `-- name: NextDeploymentVersion :one
SELECT COALESCE(MAX(version), 0) + 1 AS version
FROM deployments
WHERE site_id = $1
`

func (q *Queries) NextDeploymentVersion(ctx context.Context, siteID string) (int32, error) {
	row := q.db.QueryRow(ctx, nextDeploymentVersion, siteID)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const previousValidatedDeployment = `-- name: PreviousValidatedDeployment :one
SELECT id, site_id, version, status, bundle_ref, unpacked_path, manifest_json, validation_json, created_by_type, created_by_id, created_at, activated_at
FROM deployments
WHERE site_id = $1 AND id <> $2 AND status IN ('validated', 'superseded', 'active')
ORDER BY version DESC
LIMIT 1
`

type PreviousValidatedDeploymentParams struct {
	SiteID string `json:"site_id"`
	ID     string `json:"id"`
}

func (q *Queries) PreviousValidatedDeployment(ctx context.Context, arg PreviousValidatedDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, previousValidatedDeployment, arg.SiteID, arg.ID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Version,
		&i.Status,
		&i.BundleRef,
		&i.UnpackedPath,
		&i.ManifestJson,
		&i.ValidationJson,
		&i.CreatedByType,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.ActivatedAt,
	)
	return i, err
}

const supersedeActiveDeployments = `-- name: SupersedeActiveDeployments :exec
UPDATE deployments
SET status = 'superseded'
WHERE site_id = $1 AND status = 'active' AND id <> $2
`

type SupersedeActiveDeploymentsParams struct {
	SiteID string `json:"site_id"`
	ID     string `json:"id"`
}

func (q *Queries) SupersedeActiveDeployments(ctx context.Context, arg SupersedeActiveDeploymentsParams) error {
	_, err := q.db.Exec(ctx, supersedeActiveDeployments, arg.SiteID, arg.ID)
	return err
}

const updateDeploymentArtifacts = `-- name: UpdateDeploymentArtifacts :exec
UPDATE deployments
SET status = $2, bundle_ref = $3, unpacked_path = $4, manifest_json = $5, validation_json = $6
WHERE id = $1
`

type UpdateDeploymentArtifactsParams struct {
	ID             string `json:"id"`
	Status         string `json:"status"`
	BundleRef      string `json:"bundle_ref"`
	UnpackedPath   string `json:"unpacked_path"`
	ManifestJson   []byte `json:"manifest_json"`
	ValidationJson []byte `json:"validation_json"`
}

func (q *Queries) UpdateDeploymentArtifacts(ctx context.Context, arg UpdateDeploymentArtifactsParams) error {
	_, err := q.db.Exec(ctx, updateDeploymentArtifacts,
		arg.ID,
		arg.Status,
		arg.BundleRef,
		arg.UnpackedPath,
		arg.ManifestJson,
		arg.ValidationJson,
	)
	return err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
UPDATE deployments
SET status = $2, validation_json = $3
WHERE id = $1
`

type UpdateDeploymentStatusParams struct {
	ID             string `json:"id"`
	Status         string `json:"status"`
	ValidationJson []byte `json:"validation_json"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.db.Exec(ctx, updateDeploymentStatus, arg.ID, arg.Status, arg.ValidationJson)
	return err
}
