// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: maintenance.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAuditEventsBefore = `-- name: DeleteAuditEventsBefore :one
WITH deleted AS (
  DELETE FROM audit_log
  WHERE created_at < $1
  RETURNING id
)
SELECT COUNT(*)::bigint AS deleted_count FROM deleted
`

func (q *Queries) DeleteAuditEventsBefore(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, deleteAuditEventsBefore, createdAt)
	var deleted_count int64
	err := row.Scan(&deleted_count)
	return deleted_count, err
}

const deleteDeployment = `-- name: DeleteDeployment :exec
DELETE FROM deployments
WHERE id = $1
`

func (q *Queries) DeleteDeployment(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDeployment, id)
	return err
}

const listPrunableDeployments = `-- name: ListPrunableDeployments :many
SELECT id, site_id, version, status, bundle_ref, unpacked_path, manifest_json, validation_json, created_by_type, created_by_id, created_at, activated_at, bundle_sha256
FROM deployments
WHERE site_id = $1
  AND id <> $2
  AND status = ANY($3::text[])
  AND created_at < $4
ORDER BY created_at ASC
`

type ListPrunableDeploymentsParams struct {
	SiteID    string             `json:"site_id"`
	ID        string             `json:"id"`
	Column3   []string           `json:"column_3"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPrunableDeployments(ctx context.Context, arg ListPrunableDeploymentsParams) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listPrunableDeployments,
		arg.SiteID,
		arg.ID,
		arg.Column3,
		arg.CreatedAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Version,
			&i.Status,
			&i.BundleRef,
			&i.UnpackedPath,
			&i.ManifestJson,
			&i.ValidationJson,
			&i.CreatedByType,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.ActivatedAt,
			&i.BundleSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
