// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: memberships.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listMembershipsForUser = `-- name: ListMembershipsForUser :many
SELECT o.id AS org_id, o.slug AS org_slug, o.name AS org_name, m.role, m.created_at
FROM memberships m
JOIN orgs o ON o.id = m.org_id
WHERE m.user_id = $1
ORDER BY o.slug
`

type ListMembershipsForUserRow struct {
	OrgID     string             `json:"org_id"`
	OrgSlug   string             `json:"org_slug"`
	OrgName   string             `json:"org_name"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListMembershipsForUser(ctx context.Context, userID string) ([]ListMembershipsForUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsForUserRow{}
	for rows.Next() {
		var i ListMembershipsForUserRow
		if err := rows.Scan(
			&i.OrgID,
			&i.OrgSlug,
			&i.OrgName,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
