// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	Name            string             `json:"name"`
	Status          string             `json:"status"`
	CreatedByUserID string             `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
}

type AgentKey struct {
	ID        string             `json:"id"`
	AgentID   string             `json:"agent_id"`
	PublicKey string             `json:"public_key"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type AgentNonce struct {
	AgentID string             `json:"agent_id"`
	Nonce   string             `json:"nonce"`
	SeenAt  pgtype.Timestamptz `json:"seen_at"`
}

type AgentSiteGrant struct {
	AgentID         string             `json:"agent_id"`
	SiteID          string             `json:"site_id"`
	CanDeploy       bool               `json:"can_deploy"`
	CanRollback     bool               `json:"can_rollback"`
	AllowedChannels []string           `json:"allowed_channels"`
	AllowedPaths    []string           `json:"allowed_paths"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID           string             `json:"id"`
	OrgID        string             `json:"org_id"`
	ActorType    string             `json:"actor_type"`
	ActorID      string             `json:"actor_id"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   string             `json:"resource_id"`
	IpAddress    string             `json:"ip_address"`
	UserAgent    string             `json:"user_agent"`
	MetadataJson []byte             `json:"metadata_json"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type DeployRun struct {
	ID                string             `json:"id"`
	SiteID            string             `json:"site_id"`
	ActorType         string             `json:"actor_type"`
	ActorID           string             `json:"actor_id"`
	AgentID           string             `json:"agent_id"`
	RequestedByUserID string             `json:"requested_by_user_id"`
	Status            string             `json:"status"`
	AllowedActions    []string           `json:"allowed_actions"`
	AllowedChannels   []string           `json:"allowed_channels"`
	AllowedPaths      []string           `json:"allowed_paths"`
	UploadTokenHash   string             `json:"upload_token_hash"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
}

type Deployment struct {
	ID             string             `json:"id"`
	SiteID         string             `json:"site_id"`
	Version        int32              `json:"version"`
	Status         string             `json:"status"`
	BundleRef      string             `json:"bundle_ref"`
	UnpackedPath   string             `json:"unpacked_path"`
	ManifestJson   []byte             `json:"manifest_json"`
	ValidationJson []byte             `json:"validation_json"`
	CreatedByType  string             `json:"created_by_type"`
	CreatedByID    string             `json:"created_by_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ActivatedAt    pgtype.Timestamptz `json:"activated_at"`
}

type Membership struct {
	OrgID     string             `json:"org_id"`
	UserID    string             `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Org struct {
	ID        string             `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PlatformAdmin struct {
	UserID    string             `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RuntimeStatus struct {
	SiteID        string             `json:"site_id"`
	OrgID         string             `json:"org_id"`
	DeploymentID  string             `json:"deployment_id"`
	Hosts         []string           `json:"hosts"`
	Status        string             `json:"status"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	LastError     string             `json:"last_error"`
	RequestsTotal int64              `json:"requests_total"`
	ErrorsTotal   int64              `json:"errors_total"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type SchemaMigration struct {
	Name      string             `json:"name"`
	AppliedAt pgtype.Timestamptz `json:"applied_at"`
}

type Site struct {
	ID                 string             `json:"id"`
	OrgID              string             `json:"org_id"`
	Slug               string             `json:"slug"`
	Name               string             `json:"name"`
	PrimaryHost        string             `json:"primary_host"`
	Status             string             `json:"status"`
	ActiveDeploymentID string             `json:"active_deployment_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type SiteCapability struct {
	SiteID     string             `json:"site_id"`
	Capability string             `json:"capability"`
	Enabled    bool               `json:"enabled"`
	ConfigJson []byte             `json:"config_json"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type SiteDomain struct {
	ID                string             `json:"id"`
	SiteID            string             `json:"site_id"`
	Hostname          string             `json:"hostname"`
	Status            string             `json:"status"`
	VerificationToken string             `json:"verification_token"`
	VerifiedAt        pgtype.Timestamptz `json:"verified_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type SiteQuota struct {
	SiteID           string             `json:"site_id"`
	BundleMaxBytes   int64              `json:"bundle_max_bytes"`
	DbSoftMaxBytes   int64              `json:"db_soft_max_bytes"`
	DbHardMaxBytes   int64              `json:"db_hard_max_bytes"`
	RequestTimeoutMs int32              `json:"request_timeout_ms"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID          string             `json:"id"`
	Issuer      string             `json:"issuer"`
	Subject     string             `json:"subject"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	DisabledAt  pgtype.Timestamptz `json:"disabled_at"`
}
