// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: orgs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMembership = `-- name: AddMembership :exec
INSERT INTO memberships (org_id, user_id, role, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (org_id, user_id)
DO UPDATE SET role = EXCLUDED.role
`

type AddMembershipParams struct {
	OrgID     string             `json:"org_id"`
	UserID    string             `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AddMembership(ctx context.Context, arg AddMembershipParams) error {
	_, err := q.db.Exec(ctx, addMembership,
		arg.OrgID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const createOrg = `-- name: CreateOrg :one
INSERT INTO orgs (id, slug, name, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, slug, name, created_at
`

type CreateOrgParams struct {
	ID        string             `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, createOrg,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.CreatedAt,
	)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getMembershipRole = `-- name: GetMembershipRole :one
SELECT role
FROM memberships
WHERE org_id = $1 AND user_id = $2
`

type GetMembershipRoleParams struct {
	OrgID  string `json:"org_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetMembershipRole(ctx context.Context, arg GetMembershipRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getMembershipRole, arg.OrgID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getOrg = `-- name: GetOrg :one
SELECT id, slug, name, created_at
FROM orgs
WHERE id = $1
`

func (q *Queries) GetOrg(ctx context.Context, id string) (Org, error) {
	row := q.db.QueryRow(ctx, getOrg, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listOrgsForUser = `-- name: ListOrgsForUser :many
SELECT o.id, o.slug, o.name, o.created_at
FROM orgs o
JOIN memberships m ON m.org_id = o.id
WHERE m.user_id = $1
ORDER BY o.slug
`

func (q *Queries) ListOrgsForUser(ctx context.Context, userID string) ([]Org, error) {
	rows, err := q.db.Query(ctx, listOrgsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Org{}
	for rows.Next() {
		var i Org
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
