// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: runtime_status.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRuntimeStatus = `-- name: GetRuntimeStatus :one
SELECT site_id, org_id, deployment_id, hosts, status, started_at, last_error, requests_total, errors_total, updated_at
FROM runtime_status
WHERE site_id = $1
`

func (q *Queries) GetRuntimeStatus(ctx context.Context, siteID string) (RuntimeStatus, error) {
	row := q.db.QueryRow(ctx, getRuntimeStatus, siteID)
	var i RuntimeStatus
	err := row.Scan(
		&i.SiteID,
		&i.OrgID,
		&i.DeploymentID,
		&i.Hosts,
		&i.Status,
		&i.StartedAt,
		&i.LastError,
		&i.RequestsTotal,
		&i.ErrorsTotal,
		&i.UpdatedAt,
	)
	return i, err
}

const listRuntimeStatuses = `-- name: ListRuntimeStatuses :many
SELECT site_id, org_id, deployment_id, hosts, status, started_at, last_error, requests_total, errors_total, updated_at
FROM runtime_status
ORDER BY site_id
`

func (q *Queries) ListRuntimeStatuses(ctx context.Context) ([]RuntimeStatus, error) {
	rows, err := q.db.Query(ctx, listRuntimeStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RuntimeStatus{}
	for rows.Next() {
		var i RuntimeStatus
		if err := rows.Scan(
			&i.SiteID,
			&i.OrgID,
			&i.DeploymentID,
			&i.Hosts,
			&i.Status,
			&i.StartedAt,
			&i.LastError,
			&i.RequestsTotal,
			&i.ErrorsTotal,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileStaleRuntimeStatuses = `-- name: ReconcileStaleRuntimeStatuses :exec
UPDATE runtime_status
SET status = 'stopped', last_error = $1, updated_at = $2
WHERE status IN ('starting', 'ready', 'draining')
`

type ReconcileStaleRuntimeStatusesParams struct {
	LastError string             `json:"last_error"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ReconcileStaleRuntimeStatuses(ctx context.Context, arg ReconcileStaleRuntimeStatusesParams) error {
	_, err := q.db.Exec(ctx, reconcileStaleRuntimeStatuses, arg.LastError, arg.UpdatedAt)
	return err
}

const upsertRuntimeStatus = `-- name: UpsertRuntimeStatus :exec
INSERT INTO runtime_status (site_id, org_id, deployment_id, hosts, status, started_at, last_error, requests_total, errors_total, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (site_id)
DO UPDATE SET
  org_id = EXCLUDED.org_id,
  deployment_id = EXCLUDED.deployment_id,
  hosts = EXCLUDED.hosts,
  status = EXCLUDED.status,
  started_at = EXCLUDED.started_at,
  last_error = EXCLUDED.last_error,
  requests_total = EXCLUDED.requests_total,
  errors_total = EXCLUDED.errors_total,
  updated_at = EXCLUDED.updated_at
`

type UpsertRuntimeStatusParams struct {
	SiteID        string             `json:"site_id"`
	OrgID         string             `json:"org_id"`
	DeploymentID  string             `json:"deployment_id"`
	Hosts         []string           `json:"hosts"`
	Status        string             `json:"status"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	LastError     string             `json:"last_error"`
	RequestsTotal int64              `json:"requests_total"`
	ErrorsTotal   int64              `json:"errors_total"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertRuntimeStatus(ctx context.Context, arg UpsertRuntimeStatusParams) error {
	_, err := q.db.Exec(ctx, upsertRuntimeStatus,
		arg.SiteID,
		arg.OrgID,
		arg.DeploymentID,
		arg.Hosts,
		arg.Status,
		arg.StartedAt,
		arg.LastError,
		arg.RequestsTotal,
		arg.ErrorsTotal,
		arg.UpdatedAt,
	)
	return err
}
