// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: runtime_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertRuntimeEvent = `-- name: InsertRuntimeEvent :one
INSERT INTO runtime_events (id, site_id, org_id, deployment_id, event_type, status, message, metadata_json, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, site_id, org_id, deployment_id, event_type, status, message, metadata_json, created_at
`

type InsertRuntimeEventParams struct {
	ID           string             `json:"id"`
	SiteID       string             `json:"site_id"`
	OrgID        string             `json:"org_id"`
	DeploymentID string             `json:"deployment_id"`
	EventType    string             `json:"event_type"`
	Status       string             `json:"status"`
	Message      string             `json:"message"`
	MetadataJson []byte             `json:"metadata_json"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertRuntimeEvent(ctx context.Context, arg InsertRuntimeEventParams) (RuntimeEvent, error) {
	row := q.db.QueryRow(ctx, insertRuntimeEvent,
		arg.ID,
		arg.SiteID,
		arg.OrgID,
		arg.DeploymentID,
		arg.EventType,
		arg.Status,
		arg.Message,
		arg.MetadataJson,
		arg.CreatedAt,
	)
	var i RuntimeEvent
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.OrgID,
		&i.DeploymentID,
		&i.EventType,
		&i.Status,
		&i.Message,
		&i.MetadataJson,
		&i.CreatedAt,
	)
	return i, err
}

const listRuntimeEventsBySite = `-- name: ListRuntimeEventsBySite :many
SELECT id, site_id, org_id, deployment_id, event_type, status, message, metadata_json, created_at
FROM runtime_events
WHERE site_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListRuntimeEventsBySiteParams struct {
	SiteID string `json:"site_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListRuntimeEventsBySite(ctx context.Context, arg ListRuntimeEventsBySiteParams) ([]RuntimeEvent, error) {
	rows, err := q.db.Query(ctx, listRuntimeEventsBySite, arg.SiteID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RuntimeEvent{}
	for rows.Next() {
		var i RuntimeEvent
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.OrgID,
			&i.DeploymentID,
			&i.EventType,
			&i.Status,
			&i.Message,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
