// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: sites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDefaultSiteQuota = `-- name: CreateDefaultSiteQuota :exec
INSERT INTO site_quotas (site_id, bundle_max_bytes, db_soft_max_bytes, db_hard_max_bytes, request_timeout_ms, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateDefaultSiteQuotaParams struct {
	SiteID           string             `json:"site_id"`
	BundleMaxBytes   int64              `json:"bundle_max_bytes"`
	DbSoftMaxBytes   int64              `json:"db_soft_max_bytes"`
	DbHardMaxBytes   int64              `json:"db_hard_max_bytes"`
	RequestTimeoutMs int32              `json:"request_timeout_ms"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateDefaultSiteQuota(ctx context.Context, arg CreateDefaultSiteQuotaParams) error {
	_, err := q.db.Exec(ctx, createDefaultSiteQuota,
		arg.SiteID,
		arg.BundleMaxBytes,
		arg.DbSoftMaxBytes,
		arg.DbHardMaxBytes,
		arg.RequestTimeoutMs,
		arg.UpdatedAt,
	)
	return err
}

const createSite = `-- name: CreateSite :one
INSERT INTO sites (id, org_id, slug, name, primary_host, status, active_deployment_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, '', $7)
RETURNING id, org_id, slug, name, primary_host, status, active_deployment_id, created_at
`

type CreateSiteParams struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	PrimaryHost string             `json:"primary_host"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, createSite,
		arg.ID,
		arg.OrgID,
		arg.Slug,
		arg.Name,
		arg.PrimaryHost,
		arg.Status,
		arg.CreatedAt,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.PrimaryHost,
		&i.Status,
		&i.ActiveDeploymentID,
		&i.CreatedAt,
	)
	return i, err
}

const getSite = `-- name: GetSite :one
SELECT id, org_id, slug, name, primary_host, status, active_deployment_id, created_at
FROM sites
WHERE id = $1
`

func (q *Queries) GetSite(ctx context.Context, id string) (Site, error) {
	row := q.db.QueryRow(ctx, getSite, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.PrimaryHost,
		&i.Status,
		&i.ActiveDeploymentID,
		&i.CreatedAt,
	)
	return i, err
}

const getSiteQuota = `-- name: GetSiteQuota :one
SELECT site_id, bundle_max_bytes, db_soft_max_bytes, db_hard_max_bytes, request_timeout_ms, updated_at
FROM site_quotas
WHERE site_id = $1
`

func (q *Queries) GetSiteQuota(ctx context.Context, siteID string) (SiteQuota, error) {
	row := q.db.QueryRow(ctx, getSiteQuota, siteID)
	var i SiteQuota
	err := row.Scan(
		&i.SiteID,
		&i.BundleMaxBytes,
		&i.DbSoftMaxBytes,
		&i.DbHardMaxBytes,
		&i.RequestTimeoutMs,
		&i.UpdatedAt,
	)
	return i, err
}

const listSitesByOrg = `-- name: ListSitesByOrg :many
SELECT id, org_id, slug, name, primary_host, status, active_deployment_id, created_at
FROM sites
WHERE org_id = $1
ORDER BY slug
`

func (q *Queries) ListSitesByOrg(ctx context.Context, orgID string) ([]Site, error) {
	rows, err := q.db.Query(ctx, listSitesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Site{}
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Slug,
			&i.Name,
			&i.PrimaryHost,
			&i.Status,
			&i.ActiveDeploymentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSiteActiveDeployment = `-- name: UpdateSiteActiveDeployment :exec
UPDATE sites
SET active_deployment_id = $2, status = 'active'
WHERE id = $1
`

type UpdateSiteActiveDeploymentParams struct {
	ID                 string `json:"id"`
	ActiveDeploymentID string `json:"active_deployment_id"`
}

func (q *Queries) UpdateSiteActiveDeployment(ctx context.Context, arg UpdateSiteActiveDeploymentParams) error {
	_, err := q.db.Exec(ctx, updateSiteActiveDeployment, arg.ID, arg.ActiveDeploymentID)
	return err
}

const updateSiteStatus = `-- name: UpdateSiteStatus :exec
UPDATE sites
SET status = $2
WHERE id = $1
`

type UpdateSiteStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateSiteStatus(ctx context.Context, arg UpdateSiteStatusParams) error {
	_, err := q.db.Exec(ctx, updateSiteStatus, arg.ID, arg.Status)
	return err
}
