// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: sites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDefaultSiteQuota = `-- name: CreateDefaultSiteQuota :exec
INSERT INTO site_quotas (site_id, bundle_max_bytes, db_soft_max_bytes, db_hard_max_bytes, request_timeout_ms, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateDefaultSiteQuotaParams struct {
	SiteID           string             `json:"site_id"`
	BundleMaxBytes   int64              `json:"bundle_max_bytes"`
	DbSoftMaxBytes   int64              `json:"db_soft_max_bytes"`
	DbHardMaxBytes   int64              `json:"db_hard_max_bytes"`
	RequestTimeoutMs int32              `json:"request_timeout_ms"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateDefaultSiteQuota(ctx context.Context, arg CreateDefaultSiteQuotaParams) error {
	_, err := q.db.Exec(ctx, createDefaultSiteQuota,
		arg.SiteID,
		arg.BundleMaxBytes,
		arg.DbSoftMaxBytes,
		arg.DbHardMaxBytes,
		arg.RequestTimeoutMs,
		arg.UpdatedAt,
	)
	return err
}

const createSite = `-- name: CreateSite :one
INSERT INTO sites (id, org_id, slug, name, primary_host, status, active_deployment_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, '', $7)
RETURNING id, org_id, slug, name, primary_host, status, active_deployment_id, created_at
`

type CreateSiteParams struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	PrimaryHost string             `json:"primary_host"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, createSite,
		arg.ID,
		arg.OrgID,
		arg.Slug,
		arg.Name,
		arg.PrimaryHost,
		arg.Status,
		arg.CreatedAt,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.PrimaryHost,
		&i.Status,
		&i.ActiveDeploymentID,
		&i.CreatedAt,
	)
	return i, err
}

const createSiteDomain = `-- name: CreateSiteDomain :one
INSERT INTO site_domains (id, site_id, hostname, status, verification_token, verified_at, created_at)
VALUES ($1, $2, $3, $4, $5, NULL, $6)
RETURNING id, site_id, hostname, status, verification_token, verified_at, created_at
`

type CreateSiteDomainParams struct {
	ID                string             `json:"id"`
	SiteID            string             `json:"site_id"`
	Hostname          string             `json:"hostname"`
	Status            string             `json:"status"`
	VerificationToken string             `json:"verification_token"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateSiteDomain(ctx context.Context, arg CreateSiteDomainParams) (SiteDomain, error) {
	row := q.db.QueryRow(ctx, createSiteDomain,
		arg.ID,
		arg.SiteID,
		arg.Hostname,
		arg.Status,
		arg.VerificationToken,
		arg.CreatedAt,
	)
	var i SiteDomain
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Hostname,
		&i.Status,
		&i.VerificationToken,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSiteConfig = `-- name: DeleteSiteConfig :exec
DELETE FROM site_config
WHERE site_id = $1 AND key = $2
`

type DeleteSiteConfigParams struct {
	SiteID string `json:"site_id"`
	Key    string `json:"key"`
}

func (q *Queries) DeleteSiteConfig(ctx context.Context, arg DeleteSiteConfigParams) error {
	_, err := q.db.Exec(ctx, deleteSiteConfig, arg.SiteID, arg.Key)
	return err
}

const deleteSiteDomain = `-- name: DeleteSiteDomain :exec
DELETE FROM site_domains
WHERE id = $1
`

func (q *Queries) DeleteSiteDomain(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSiteDomain, id)
	return err
}

const getSite = `-- name: GetSite :one
SELECT id, org_id, slug, name, primary_host, status, active_deployment_id, created_at
FROM sites
WHERE id = $1
`

func (q *Queries) GetSite(ctx context.Context, id string) (Site, error) {
	row := q.db.QueryRow(ctx, getSite, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.PrimaryHost,
		&i.Status,
		&i.ActiveDeploymentID,
		&i.CreatedAt,
	)
	return i, err
}

const getSiteDomain = `-- name: GetSiteDomain :one
SELECT id, site_id, hostname, status, verification_token, verified_at, created_at
FROM site_domains
WHERE id = $1
`

func (q *Queries) GetSiteDomain(ctx context.Context, id string) (SiteDomain, error) {
	row := q.db.QueryRow(ctx, getSiteDomain, id)
	var i SiteDomain
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Hostname,
		&i.Status,
		&i.VerificationToken,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSiteQuota = `-- name: GetSiteQuota :one
SELECT site_id, bundle_max_bytes, db_soft_max_bytes, db_hard_max_bytes, request_timeout_ms, updated_at
FROM site_quotas
WHERE site_id = $1
`

func (q *Queries) GetSiteQuota(ctx context.Context, siteID string) (SiteQuota, error) {
	row := q.db.QueryRow(ctx, getSiteQuota, siteID)
	var i SiteQuota
	err := row.Scan(
		&i.SiteID,
		&i.BundleMaxBytes,
		&i.DbSoftMaxBytes,
		&i.DbHardMaxBytes,
		&i.RequestTimeoutMs,
		&i.UpdatedAt,
	)
	return i, err
}

const listSiteCapabilities = `-- name: ListSiteCapabilities :many
SELECT site_id, capability, enabled, config_json, updated_at
FROM site_capabilities
WHERE site_id = $1
ORDER BY capability
`

func (q *Queries) ListSiteCapabilities(ctx context.Context, siteID string) ([]SiteCapability, error) {
	rows, err := q.db.Query(ctx, listSiteCapabilities, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiteCapability{}
	for rows.Next() {
		var i SiteCapability
		if err := rows.Scan(
			&i.SiteID,
			&i.Capability,
			&i.Enabled,
			&i.ConfigJson,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteConfig = `-- name: ListSiteConfig :many
SELECT site_id, key, value_json, updated_at
FROM site_config
WHERE site_id = $1
ORDER BY key
`

func (q *Queries) ListSiteConfig(ctx context.Context, siteID string) ([]SiteConfig, error) {
	rows, err := q.db.Query(ctx, listSiteConfig, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiteConfig{}
	for rows.Next() {
		var i SiteConfig
		if err := rows.Scan(
			&i.SiteID,
			&i.Key,
			&i.ValueJson,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteDomains = `-- name: ListSiteDomains :many
SELECT id, site_id, hostname, status, verification_token, verified_at, created_at
FROM site_domains
WHERE site_id = $1
ORDER BY hostname
`

func (q *Queries) ListSiteDomains(ctx context.Context, siteID string) ([]SiteDomain, error) {
	rows, err := q.db.Query(ctx, listSiteDomains, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiteDomain{}
	for rows.Next() {
		var i SiteDomain
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Hostname,
			&i.Status,
			&i.VerificationToken,
			&i.VerifiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSitesByOrg = `-- name: ListSitesByOrg :many
SELECT id, org_id, slug, name, primary_host, status, active_deployment_id, created_at
FROM sites
WHERE org_id = $1
ORDER BY slug
`

func (q *Queries) ListSitesByOrg(ctx context.Context, orgID string) ([]Site, error) {
	rows, err := q.db.Query(ctx, listSitesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Site{}
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Slug,
			&i.Name,
			&i.PrimaryHost,
			&i.Status,
			&i.ActiveDeploymentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifiedSiteDomains = `-- name: ListVerifiedSiteDomains :many
SELECT id, site_id, hostname, status, verification_token, verified_at, created_at
FROM site_domains
WHERE site_id = $1 AND status = 'verified'
ORDER BY hostname
`

func (q *Queries) ListVerifiedSiteDomains(ctx context.Context, siteID string) ([]SiteDomain, error) {
	rows, err := q.db.Query(ctx, listVerifiedSiteDomains, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiteDomain{}
	for rows.Next() {
		var i SiteDomain
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Hostname,
			&i.Status,
			&i.VerificationToken,
			&i.VerifiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSiteActiveDeployment = `-- name: UpdateSiteActiveDeployment :exec
UPDATE sites
SET active_deployment_id = $2, status = 'active'
WHERE id = $1
`

type UpdateSiteActiveDeploymentParams struct {
	ID                 string `json:"id"`
	ActiveDeploymentID string `json:"active_deployment_id"`
}

func (q *Queries) UpdateSiteActiveDeployment(ctx context.Context, arg UpdateSiteActiveDeploymentParams) error {
	_, err := q.db.Exec(ctx, updateSiteActiveDeployment, arg.ID, arg.ActiveDeploymentID)
	return err
}

const updateSiteStatus = `-- name: UpdateSiteStatus :exec
UPDATE sites
SET status = $2
WHERE id = $1
`

type UpdateSiteStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateSiteStatus(ctx context.Context, arg UpdateSiteStatusParams) error {
	_, err := q.db.Exec(ctx, updateSiteStatus, arg.ID, arg.Status)
	return err
}

const upsertSiteCapability = `-- name: UpsertSiteCapability :exec
INSERT INTO site_capabilities (site_id, capability, enabled, config_json, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (site_id, capability)
DO UPDATE SET enabled = EXCLUDED.enabled, config_json = EXCLUDED.config_json, updated_at = EXCLUDED.updated_at
`

type UpsertSiteCapabilityParams struct {
	SiteID     string             `json:"site_id"`
	Capability string             `json:"capability"`
	Enabled    bool               `json:"enabled"`
	ConfigJson []byte             `json:"config_json"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertSiteCapability(ctx context.Context, arg UpsertSiteCapabilityParams) error {
	_, err := q.db.Exec(ctx, upsertSiteCapability,
		arg.SiteID,
		arg.Capability,
		arg.Enabled,
		arg.ConfigJson,
		arg.UpdatedAt,
	)
	return err
}

const upsertSiteConfig = `-- name: UpsertSiteConfig :exec
INSERT INTO site_config (site_id, key, value_json, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (site_id, key)
DO UPDATE SET value_json = EXCLUDED.value_json, updated_at = EXCLUDED.updated_at
`

type UpsertSiteConfigParams struct {
	SiteID    string             `json:"site_id"`
	Key       string             `json:"key"`
	ValueJson []byte             `json:"value_json"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertSiteConfig(ctx context.Context, arg UpsertSiteConfigParams) error {
	_, err := q.db.Exec(ctx, upsertSiteConfig,
		arg.SiteID,
		arg.Key,
		arg.ValueJson,
		arg.UpdatedAt,
	)
	return err
}

const verifySiteDomain = `-- name: VerifySiteDomain :one
UPDATE site_domains
SET status = 'verified', verified_at = $2
WHERE id = $1
RETURNING id, site_id, hostname, status, verification_token, verified_at, created_at
`

type VerifySiteDomainParams struct {
	ID         string             `json:"id"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
}

func (q *Queries) VerifySiteDomain(ctx context.Context, arg VerifySiteDomainParams) (SiteDomain, error) {
	row := q.db.QueryRow(ctx, verifySiteDomain, arg.ID, arg.VerifiedAt)
	var i SiteDomain
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Hostname,
		&i.Status,
		&i.VerificationToken,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}
