// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPlatformAdmin = `-- name: AddPlatformAdmin :exec
INSERT INTO platform_admins (user_id, created_at)
VALUES ($1, $2)
ON CONFLICT (user_id) DO NOTHING
`

type AddPlatformAdminParams struct {
	UserID    string             `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AddPlatformAdmin(ctx context.Context, arg AddPlatformAdminParams) error {
	_, err := q.db.Exec(ctx, addPlatformAdmin, arg.UserID, arg.CreatedAt)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, issuer, subject, email, display_name, created_at, last_login_at
FROM users
WHERE id = $1
`

type GetUserRow struct {
	ID          string             `json:"id"`
	Issuer      string             `json:"issuer"`
	Subject     string             `json:"subject"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) GetUser(ctx context.Context, id string) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const isPlatformAdmin = `-- name: IsPlatformAdmin :one
SELECT EXISTS (SELECT 1 FROM platform_admins WHERE user_id = $1)
`

func (q *Queries) IsPlatformAdmin(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, isPlatformAdmin, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertUserFromOIDC = `-- name: UpsertUserFromOIDC :one
INSERT INTO users (id, issuer, subject, email, display_name, created_at, last_login_at)
VALUES ($1, $2, $3, $4, $5, $6, $6)
ON CONFLICT (issuer, subject)
DO UPDATE SET
  email = EXCLUDED.email,
  display_name = EXCLUDED.display_name,
  last_login_at = EXCLUDED.last_login_at
RETURNING id, issuer, subject, email, display_name, created_at, last_login_at
`

type UpsertUserFromOIDCParams struct {
	ID          string             `json:"id"`
	Issuer      string             `json:"issuer"`
	Subject     string             `json:"subject"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type UpsertUserFromOIDCRow struct {
	ID          string             `json:"id"`
	Issuer      string             `json:"issuer"`
	Subject     string             `json:"subject"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) UpsertUserFromOIDC(ctx context.Context, arg UpsertUserFromOIDCParams) (UpsertUserFromOIDCRow, error) {
	row := q.db.QueryRow(ctx, upsertUserFromOIDC,
		arg.ID,
		arg.Issuer,
		arg.Subject,
		arg.Email,
		arg.DisplayName,
		arg.CreatedAt,
	)
	var i UpsertUserFromOIDCRow
	err := row.Scan(
		&i.ID,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
