import type { Meta, StoryObj } from '@storybook/react';
import { http, HttpResponse } from 'msw';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { AdminAuditPage } from './AdminAuditPage';
const Wrapped = () => <MemoryRouter initialEntries={['/admin/audit']}><Routes><Route path="/admin/audit" element={<AdminAuditPage />} /></Routes></MemoryRouter>;
const meta = { title: 'Admin Pages/AdminAuditPage', component: Wrapped } satisfies Meta<typeof Wrapped>;
export default meta; type Story = StoryObj<typeof meta>;
export const Populated: Story = {};
export const Empty: Story = { parameters: { msw: { handlers: [http.get('/api/v1/admin/audit', () => HttpResponse.json([]))] } } };
export const Forbidden: Story = { parameters: { msw: { handlers: [http.get('/api/v1/admin/audit', () => HttpResponse.json({ error: 'platform admin required' }, { status: 403 }))] } } };
